import type { Challenge } from "../shared/types";

export const SEED_CHALLENGES: Omit<Challenge, "completedBy">[] = [
  {
    id: "ch-charging-bull",
    name: "That's totally bull",
    description: "Come up with 2 lies and one truth about one team member. Send to another other team. If they pick a lie, you win",
    type: "fixed",
    lat: 40.7055,
    lng: -74.0134,
    reward: 40,
    rewardDescription: "Earn 5 chips",
  },
  {
    id: "ch-times-sq-count",
    name: "Tourist Counter",
    description: "Stand in Times Square for 1 minute. How many people ask you to take their photo? Earn 3x that number in chips (min 3).",
    type: "variable",
    lat: 40.7580,
    lng: -73.9855,
    reward: 3,
    rewardDescription: "Earn 3x your count (min 3 chips)",
  },
  {
    id: "ch-central-park-bench",
    name: "Park Bench Philosopher",
    description: "Sit on a bench in Central Park for 2 minutes without looking at your phone",
    type: "fixed",
    lat: 40.7712,
    lng: -73.9743,
    reward: 4,
    rewardDescription: "Earn 4 chips",
  },
  {
    id: "ch-grand-central-ceiling",
    name: "Stargazer",
    description: "Find the backwards constellation on the Grand Central ceiling. Which zodiac sign is in the center?",
    type: "fixed",
    lat: 40.7527,
    lng: -73.9772,
    reward: 6,
    rewardDescription: "Earn 6 chips",
  },
  {
    id: "ch-busses-14st",
    name: "Bus Spotter",
    description: "Stand at 14th St and count how many buses pass in 2 minutes. Earn 2x your count in chips.",
    type: "variable",
    lat: 40.7378,
    lng: -74.0003,
    reward: 2,
    rewardDescription: "Earn 2x your bus count",
  },
  {
    id: "ch-washington-sq",
    name: "Arch Rival",
    description: "Walk through the Washington Square Arch from north to south",
    type: "fixed",
    lat: 40.7308,
    lng: -73.9973,
    reward: 4,
    rewardDescription: "Earn 4 chips",
  },
  {
    id: "ch-high-line-walk",
    name: "High Line Hustle",
    description: "Walk the entire High Line from start to finish (either direction)",
    type: "fixed",
    lat: 40.7480,
    lng: -74.0048,
    reward: 8,
    rewardDescription: "Earn 8 chips",
  },
  {
    id: "ch-chinatown-dumplings",
    name: "Dumpling Dash",
    description: "Buy dumplings from any Chinatown shop. How many can you eat in 2 minutes? Earn 1 chip per dumpling.",
    type: "variable",
    lat: 40.7158,
    lng: -73.9970,
    reward: 1,
    rewardDescription: "Earn 1 chip per dumpling eaten",
  },
  {
    id: "ch-multiplier-flatiron",
    name: "Flatiron Multiplier",
    description: "Find the Flatiron Building and count its floors from the outside. If correct (22), earn a 50% chip multiplier!",
    type: "multiplier",
    lat: 40.7411,
    lng: -73.9897,
    reward: 50,
    rewardDescription: "50% multiplier on your banked chips",
  },
  {
    id: "ch-steal-brooklyn-bridge",
    name: "Bridge Heist",
    description: "Walk to the Manhattan side of the Brooklyn Bridge pedestrian entrance. Steal 25% of an opponent's chips!",
    type: "steal",
    lat: 40.7081,
    lng: -74.0037,
    reward: 25,
    rewardDescription: "Steal 25% of opponent's banked chips",
  },
  {
    id: "ch-subway-musician",
    name: "Underground Talent",
    description: "Find a subway musician and listen to a full song. Tip them if you can!",
    type: "fixed",
    lat: 40.7559,
    lng: -73.9870,
    reward: 5,
    rewardDescription: "Earn 5 chips",
  },
  {
    id: "ch-pizza-fold",
    name: "The Perfect Fold",
    description: "Buy a slice of pizza and eat it folded New York style. No fork and knife!",
    type: "fixed",
    lat: 40.7306,
    lng: -73.9892,
    reward: 4,
    rewardDescription: "Earn 4 chips",
  },
  {
    id: "ch-steal-harlem",
    name: "Uptown Takedown",
    description: "Visit the Apollo Theater marquee. Steal 30% of your opponent's chips!",
    type: "steal",
    lat: 40.8099,
    lng: -73.9500,
    reward: 30,
    rewardDescription: "Steal 30% of opponent's banked chips",
  },
  {
    id: "ch-hudson-yards",
    name: "The Vessel Viewpoint",
    description: "Count the staircases visible from ground level at The Vessel. Earn 2x your count.",
    type: "variable",
    lat: 40.7540,
    lng: -74.0021,
    reward: 2,
    rewardDescription: "Earn 2x your staircase count",
  },
  {
    id: "ch-multiplier-columbus",
    name: "Circle of Fortune",
    description: "Do a full lap around the Columbus Circle roundabout on foot. 40% chip multiplier!",
    type: "multiplier",
    lat: 40.7681,
    lng: -73.9819,
    reward: 40,
    rewardDescription: "40% multiplier on your banked chips",
  },
  // Call Your Shot challenges
  {
    id: "ch-call-bus",
    name: "Call Your Shot: Buses",
    description: "How many buses will pass your location in the next 60 seconds? Call your number before starting — go under and no points! 1 chip per bus.",
    type: "variable",
    lat: 40.7561,
    lng: -73.9900,
    reward: 1,
    rewardDescription: "1 chip per bus (0 if under your call)",
    customScoring: "call-your-shot-bus",
    resultLabel: "Buses counted",
  },
  {
    id: "ch-call-vendors",
    name: "Call Your Shot: Street Vendors",
    description: "How many street vendors can you find in one minute? Call your number before starting — go under and no points! 1 chip per vendor.",
    type: "variable",
    lat: 40.7510,
    lng: -73.9930,
    reward: 1,
    rewardDescription: "1 chip per vendor (0 if under your call)",
    customScoring: "call-your-shot-vendors",
    resultLabel: "Vendors found",
  },
  {
    id: "ch-call-statues",
    name: "Call Your Shot: Central Park Statues",
    description: "How many statues can you find in Central Park? Call your number before starting — go under and no points! 1 chip per statue.",
    type: "variable",
    lat: 40.7736,
    lng: -73.9712,
    reward: 1,
    rewardDescription: "1 chip per statue (0 if under your call)",
    customScoring: "call-your-shot-statues",
    resultLabel: "Statues found",
  },
  {
    id: "ch-call-logos",
    name: "Call Your Shot: Corporate Logos",
    description: "How many corporate logos can you spot in 5 minutes? 2 chips each, but you must find at least 30 or you get nothing!",
    type: "variable",
    lat: 40.7614,
    lng: -73.9776,
    reward: 2,
    rewardDescription: "2 chips per logo (minimum 30 to score)",
    customScoring: "call-your-shot-logos",
    resultLabel: "Logos spotted",
  },
  {
    id: "ch-one-leg",
    name: "One Leg Stand",
    description: "How long can one person stand on one leg? 60 chips for the first minute, then 10 chips per additional 10 seconds after (round down).",
    type: "variable",
    lat: 40.7440,
    lng: -73.9920,
    reward: 0,
    rewardDescription: "60 chips for 1 min + 10 per extra 10 sec",
    customScoring: "one-leg-stand",
    resultLabel: "Total seconds stood",
  },
  {
    id: "ch-call-water-towers",
    name: "Call Your Shot: Water Towers",
    description: "How many wooden water towers can you find? Call your number before starting — go under and no points! 1 chip per water tower.",
    type: "variable",
    lat: 40.7243,
    lng: -73.9976,
    reward: 1,
    rewardDescription: "1 chip per water tower (0 if under your call)",
    customScoring: "call-your-shot-water-towers",
    resultLabel: "Water towers found",
  },
  // Steals
  {
    id: "ch-steal-apple-store",
    name: "Apple Store Sprint",
    description: "Get to an Apple Store in the next 10 minutes (15 min walk on Google Maps or a sneaky 5 min subway ride). Steal 20% of opponent's chips!",
    type: "steal",
    lat: 40.7639,
    lng: -73.9722,
    reward: 20,
    rewardDescription: "Steal 20% of opponent's banked chips",
    customScoring: "steal-apple-store",
  },
  {
    id: "ch-steal-countdown",
    name: "Blind Countdown",
    description: "Without looking, cover your eyes and count as close as you can to 60 seconds. Steal 20% minus 1% for each second you're off!",
    type: "steal",
    lat: 40.7484,
    lng: -73.9857,
    reward: 20,
    rewardDescription: "Steal (20 - seconds off)% of opponent's chips",
    customScoring: "steal-countdown",
    resultLabel: "Seconds you counted to",
  },
  // Multipliers
  {
    id: "ch-mult-5-stops",
    name: "Express Run",
    description: "Travel at least 5 subway stops in the next 15 minutes. 50% multiplier on your banked chips!",
    type: "multiplier",
    lat: 40.7527,
    lng: -73.9772,
    reward: 50,
    rewardDescription: "50% multiplier on your banked chips",
    customScoring: "multiplier-5-stops",
  },
  {
    id: "ch-mult-other-river",
    name: "River Crossing",
    description: "Get to the other river from where you currently are. 50% multiplier on your banked chips!",
    type: "multiplier",
    lat: 40.7484,
    lng: -73.9857,
    reward: 50,
    rewardDescription: "50% multiplier on your banked chips",
    customScoring: "multiplier-other-river",
  },
  {
    id: "ch-mult-rat",
    name: "Rat Paparazzi",
    description: "Photograph a live rat (start at Rat Rock in Central Park). 50% multiplier on your banked chips!",
    type: "multiplier",
    lat: 40.7685,
    lng: -73.9808,
    reward: 50,
    rewardDescription: "50% multiplier on your banked chips",
    customScoring: "multiplier-rat",
  },
  // Normal challenges
  {
    id: "ch-strava-message",
    name: "Strava Speller",
    description: "Walk a route on Strava to spell a message. Have the other team guess. They get 2 attempts before it counts — no collusion!",
    type: "fixed",
    lat: 40.7484,
    lng: -73.9857,
    reward: 75,
    rewardDescription: "Earn 75 chips",
    customScoring: "strava-message",
  },
  {
    id: "ch-timed-upper-west",
    name: "East, I Thought You Said Weast!",
    description: "Get to any station on the Upper West Side in the next 10 minutes for 40 points.",
    type: "fixed",
    lat: 40.7736,
    lng: -73.9566,
    reward: 40,
    rewardDescription: "Earn 40 chips",
    imageUrl: "https://y.yarn.co/9ce03beb-eaac-48fc-a44a-73c6dad41117_text.gif",
  },
  {
    id: "ch-timed-hotdog",
    name: "Hot Dog Stand Sprint",
    description: "Find the nearest hot dog cart and buy one. How long did it take? Earn (10 - minutes) chips, minimum 2.",
    type: "variable",
    lat: 40.7484,
    lng: -73.9857,
    reward: 1,
    rewardDescription: "Earn (10 - minutes to find) chips",
  },
  {
    id: "ch-timed-cab-count",
    name: "Yellow Cab Census",
    description: "Count yellow cabs passing your location in 1 minute. Earn 1 chip per 5 cabs spotted.",
    type: "variable",
    lat: 40.7505,
    lng: -73.9935,
    reward: 1,
    rewardDescription: "1 chip per 5 cabs counted",
  },
  {
    id: "ch-timed-multiplier-empire",
    name: "Empire State Gambit",
    description: "Take a photo where the Empire State Building is clearly visible. 60% chip multiplier!",
    type: "multiplier",
    lat: 40.7484,
    lng: -73.9857,
    reward: 60,
    rewardDescription: "60% multiplier on your banked chips",
  },
  {
    id: "ch-timed-steal-wall-st",
    name: "Wall Street Raid",
    description: "Touch the NYSE building facade. Steal 35% of your opponent's banked chips!",
    type: "steal",
    lat: 40.7069,
    lng: -74.0113,
    reward: 35,
    rewardDescription: "Steal 35% of opponent's banked chips",
  },
  {
    id: "ch-timed-final-sprint",
    name: "Final Sprint Bonus",
    description: "Visit any 3 uncaptured stations within 15 minutes. Self-report your success!",
    type: "fixed",
    lat: 40.7527,
    lng: -73.9772,
    reward: 10,
    rewardDescription: "Earn 10 chips",
  },
];

export const RESERVE_CHALLENGES: Omit<Challenge, "completedBy">[] = [
  {
    id: "ch-reserve-oculus",
    name: "Oculus Explorer",
    description: "Find the Oculus at the World Trade Center. How many white ribs can you count on one side? Earn 1 chip per rib.",
    type: "variable",
    lat: 40.7112,
    lng: -74.0113,
    reward: 1,
    rewardDescription: "1 chip per rib counted",
  },
  {
    id: "ch-reserve-bodega-cat",
    name: "Bodega Cat Hunt",
    description: "Find a bodega with a cat inside. Take a photo (honor system)!",
    type: "fixed",
    lat: 40.7282,
    lng: -73.9907,
    reward: 6,
    rewardDescription: "Earn 6 chips",
  },
  {
    id: "ch-reserve-subway-performer",
    name: "Underground Talent Show",
    description: "Watch a subway performer for at least one full song. What instrument did they play?",
    type: "fixed",
    lat: 40.7559,
    lng: -73.9870,
    reward: 4,
    rewardDescription: "Earn 4 chips",
  },
  {
    id: "ch-reserve-stairs-challenge",
    name: "Stairway to Heaven",
    description: "Find a station with no elevator or escalator and climb the full flight. How many steps? Earn 1 chip per 10 steps.",
    type: "variable",
    lat: 40.7412,
    lng: -73.9893,
    reward: 1,
    rewardDescription: "1 chip per 10 steps",
  },
  {
    id: "ch-reserve-food-cart",
    name: "Halal Cart Challenge",
    description: "Buy a meal from a halal cart. Earn chips equal to how many dollars you spent (rounded down).",
    type: "variable",
    lat: 40.7614,
    lng: -73.9776,
    reward: 1,
    rewardDescription: "1 chip per dollar spent",
  },
  {
    id: "ch-reserve-multiplier-rockefeller",
    name: "Top of the Rock",
    description: "Stand in the Rockefeller Center plaza. Earn a 35% chip multiplier!",
    type: "multiplier",
    lat: 40.7587,
    lng: -73.9787,
    reward: 35,
    rewardDescription: "35% multiplier on your banked chips",
  },
  {
    id: "ch-reserve-steal-penn",
    name: "Penn Station Pickpocket",
    description: "Navigate through Penn Station from the 1/2/3 entrance to the A/C/E side. Steal 20% of opponent's chips!",
    type: "steal",
    lat: 40.7506,
    lng: -73.9935,
    reward: 20,
    rewardDescription: "Steal 20% of opponent's banked chips",
  },
  {
    id: "ch-reserve-dog-count",
    name: "Dog Spotter",
    description: "Stand in any park for 3 minutes. How many dogs do you see? Earn 2 chips per dog.",
    type: "variable",
    lat: 40.7712,
    lng: -73.9743,
    reward: 2,
    rewardDescription: "2 chips per dog spotted",
  },
  {
    id: "ch-reserve-ferry",
    name: "Free Ride",
    description: "Ride the Staten Island Ferry one way (it's free!). Earn chips when you arrive.",
    type: "fixed",
    lat: 40.7019,
    lng: -74.0130,
    reward: 8,
    rewardDescription: "Earn 8 chips",
  },
  {
    id: "ch-reserve-multiplier-union-sq",
    name: "Union Square Hustle",
    description: "Do a lap around the Union Square farmers market (or park if no market). 45% chip multiplier!",
    type: "multiplier",
    lat: 40.7359,
    lng: -73.9911,
    reward: 45,
    rewardDescription: "45% multiplier on your banked chips",
  },
];
